# NumPy Data Analysis Challenge

This notebook contains solutions to the NumPy Data Analysis Challenge.

## Objective

Build strong fundamentals with NumPy arrays and common numerical operations.

## Topics Covered

1. Array Creation
2. Student Marks Analysis
3. Filtering
4. Reshaping
5. Two-Dimensional Arrays
6. Mathematical Operations
7. Statistical Analysis
8. Sorting
9. Unique Values
10. Matrix Operations
11. Salary Analysis
12. Random Matrix Challenge

In [1]:
# Import numpy
import numpy as np

## 1. Array Creation

Create NumPy arrays containing:

- Numbers 1–50
- Even numbers 2–100
- Odd numbers 1–99

In [3]:
# Numbers 1-50
numbers_1_to_50 = np.arange(1, 51)
print(numbers_1_to_50)

# Even numbers 2-100
even_numbers = np.arange(2, 101, 2)
print("\n", even_numbers)

# Odd numbers 1-99
odd_numbers = np.arange(1, 100, 2)
print("\n", odd_numbers)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

 [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]

 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


## 2. Student Marks Analysis

Create a NumPy array containing the marks of 10 students and calculate:

- Total marks
- Average marks
- Maximum marks
- Minimum marks
- Median marks

In [5]:
marks = np.array([78, 85, 92, 67, 88, 73, 95, 60, 84, 91])
print(marks)

[78 85 92 67 88 73 95 60 84 91]


In [6]:
total_marks = np.sum(marks)
average_marks = np.mean(marks)
maximum_marks = np.max(marks)
minimum_marks = np.min(marks)
median_marks = np.median(marks)

print("Total Marks:", total_marks)
print("Average Marks:", average_marks)
print("Maximum Marks:", maximum_marks)
print("Minimum Marks:", minimum_marks)
print("Median Marks:", median_marks)

Total Marks: 813
Average Marks: 81.3
Maximum Marks: 95
Minimum Marks: 60
Median Marks: 84.5


## 3. Filtering

Using the student marks array, find the students scoring:

- Above 90
- Above average
- Below 70

This demonstrates Boolean filtering in NumPy.

In [16]:
# Calculate the average marks
average_marks = np.mean(marks)

# Filter the marks based on conditions
above_90 = marks[marks > 90]
above_average = marks[marks > average_marks]
below_70 = marks[marks < 70]

print("Average Marks:", average_marks)
print("Students scoring above 90:", above_90)
print("Students scoring above average:", above_average)
print("Students scoring below 70:", below_70)

Average Marks: 81.3
Students scoring above 90: [92 95 91]
Students scoring above average: [85 92 88 95 84 91]
Students scoring below 70: [67 60]


## 4. Reshaping

Create a NumPy array containing numbers from 1 to 20
and reshape it into a 4 × 5 array.

In [13]:
# Create numbers from 1 to 20
numbers = np.arange(1, 21)

# Reshape the array into 4 rows and 5 columns
reshaped_array = numbers.reshape(4, 5)

print(numbers)
print("\n", reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
print("Numbers shape:", numbers.shape)
print("Reshaped array shape:", reshaped_array.shape)

Numbers shape: (20,)
Reshaped array shape: (4, 5)


## 5. Two-Dimensional Array

Create a 3 × 3 NumPy matrix and demonstrate:

- Row selection
- Column selection
- Individual element selection

In [18]:
# Create a 3 × 3 matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix)
print("\nMatrix shape:", matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix shape: (3, 3)


In [ ]:
# Select the first row
matrix[0]

array([1, 2, 3])

In [23]:
# Select the second column
matrix[:, 1]

array([2, 5, 8])

In [26]:
# Select the element at row 2, column 2
matrix[1, 1]

np.int64(5)

## 6. Mathematical Operations

Given two NumPy arrays, perform:

- Addition
- Subtraction
- Multiplication
- Division

These operations are performed element-wise.

In [28]:
# Create the two arrays
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

print("Array A:", a)
print("Array B:", b)

Array A: [10 20 30 40 50]
Array B: [ 5 10 15 20 25]


In [29]:
# Perform mathematical operations
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [15 30 45 60 75]
Subtraction: [ 5 10 15 20 25]
Multiplication: [  50  200  450  800 1250]
Division: [2. 2. 2. 2. 2.]


## 7. Statistical Analysis

Generate 100 random numbers using NumPy and calculate:

- Mean
- Median
- Standard deviation
- Variance

In [31]:
# Generate 100 random numbers between 0 and 1
random_numbers = np.random.random(100)
random_numbers

array([0.60012677, 0.83641763, 0.23408209, 0.27163347, 0.85726029,
       0.65316666, 0.46968253, 0.23002262, 0.64151747, 0.41639419,
       0.02632725, 0.07185568, 0.72063829, 0.49608966, 0.09319154,
       0.73257904, 0.94652502, 0.22765426, 0.96660962, 0.19886434,
       0.51722567, 0.39769983, 0.91906223, 0.08111551, 0.05414247,
       0.3607864 , 0.54845449, 0.93755415, 0.37731592, 0.97749073,
       0.63759056, 0.35455711, 0.8643674 , 0.81469619, 0.42310917,
       0.87554645, 0.64397843, 0.22302953, 0.97668119, 0.27672207,
       0.38505629, 0.83381105, 0.61633498, 0.20802341, 0.04811589,
       0.74104786, 0.74723832, 0.31003496, 0.22588806, 0.3856128 ,
       0.77960446, 0.6000014 , 0.36092515, 0.26817991, 0.89583243,
       0.64325678, 0.2835894 , 0.78813098, 0.14336982, 0.16468496,
       0.5366696 , 0.78958582, 0.65555284, 0.82385914, 0.92005382,
       0.38318722, 0.5505622 , 0.22667669, 0.70475585, 0.35529746,
       0.45164817, 0.77445038, 0.54865158, 0.289055  , 0.22419

In [32]:
# Calculate statistical values
print("Mean:", np.mean(random_numbers))
print("Median:", np.median(random_numbers))
print("Standard Deviation:", np.std(random_numbers))
print("Variance:", np.var(random_numbers))

Mean: 0.4877524729293068
Median: 0.448873713382463
Standard Deviation: 0.28045106470265374
Variance: 0.07865279969285208


## 8. Sorting

Create an unsorted NumPy array and display the values in:

- Ascending order
- Descending order

In [34]:
# Sort the array in ascending order
print("Ascending Order:", np.sort(numbers))
print("Descending Order:", np.sort(numbers)[::-1])

Ascending Order: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Descending Order: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


## 9. Unique Values

Given the array:

[1, 2, 2, 3, 3, 3, 4, 5, 5, 6]

Find the unique values using NumPy.

In [36]:
# Create the array
numbers = np.array([1, 2, 2, 3, 3, 3, 4, 5, 5, 6])
print("Original Array:", numbers)
print("Unique Values:", np.unique(numbers))

Original Array: [1 2 2 3 3 3 4 5 5 6]
Unique Values: [1 2 3 4 5 6]


## 10. Matrix Operations

Create two 3 × 3 NumPy matrices and perform:

- Matrix addition
- Matrix subtraction
- Element-wise multiplication
- Matrix multiplication

In [38]:
# Create two 3 × 3 matrices
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [40]:
# Matrix Addition
print("Matrix Addition:\n", matrix_a + matrix_b)

Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [41]:
# Matrix Subtraction
print("Matrix Subtraction:\n", matrix_a - matrix_b)

Matrix Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [42]:
# Element-wise Multiplication
print("Element-wise Multiplication:\n", matrix_a * matrix_b)

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [43]:
# Matrix Multiplication
print("Matrix Multiplication:\n", np.dot(matrix_a, matrix_b))

Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## 11. Salary Analysis

Create salary data for 15 employees and find:

- Highest salary
- Lowest salary
- Average salary
- Employees earning above average

In [44]:
# Salary data for 15 employees
salaries = np.array([25000,32000,45000,28000,55000,38000,42000,30000,60000,35000,48000,27000,52000,40000,33000])
salaries

array([25000, 32000, 45000, 28000, 55000, 38000, 42000, 30000, 60000,
       35000, 48000, 27000, 52000, 40000, 33000])

In [46]:
# Find salaries above the average
above_average = salaries[salaries > np.mean(salaries)]
print("Highest Salary:", np.max(salaries))
print("Lowest Salary:", np.min(salaries))
print("Average Salary:", np.mean(salaries))
print("Employees earning above average:", above_average)

Highest Salary: 60000
Lowest Salary: 25000
Average Salary: 39333.333333333336
Employees earning above average: [45000 55000 42000 60000 48000 52000 40000]


## 12. Challenge

Generate a 5 × 5 random integer matrix and determine:

- Maximum value
- Minimum value
- Row-wise sum
- Column-wise sum
- Overall average

In [47]:
# Generate a 5 × 5 matrix of random integers from 1 to 100
random_matrix = np.random.randint(1, 101, size=(5, 5))
random_matrix

array([[99, 47, 60, 43, 24],
       [80, 85, 18, 54, 35],
       [93, 60, 99, 32, 16],
       [96, 43, 30,  9, 82],
       [12, 50, 25, 86, 91]], dtype=int32)

In [50]:
print("Maximum Value:", np.max(random_matrix))
print("Minimum Value:", np.min(random_matrix))
print("Row-wise Sum:", np.sum(random_matrix, axis=1))
print("Column-wise Sum:", np.sum(random_matrix, axis=0))
print("Overall Average:", np.mean(random_matrix))

Maximum Value: 99
Minimum Value: 9
Row-wise Sum: [273 272 300 260 264]
Column-wise Sum: [380 285 232 224 248]
Overall Average: 54.76
